# This is a basic workflow to help you get started with Actions
# Beth Test

name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - uses: actions/checkout@v2
      - name: Run API Tests
        run: newman run "tau/Lesson4/RestfulBookerBVT.postman_collection.json" -e "tau/Lesson4/Production.postman_environment.json" 
